# rabbitmq amqp configuration
amqp:
  hostname: "rabbitmq-broker"
  username: "user"
  password: "user"
  dotnet-service: "dotnetapp"
  endpoints:
    nodesStatus: UpdateNodesStatus
    updateTask: UpdateTaskCounter

# rabbitmq mqtt plugin configuration
mqtt:
  hostname: "rabbitmq-broker"
  username: "user"
  password: "user"
