# configuration of rabbitmq amqp connection
amqp:
  hostname: "rabbitmq-broker"
  username: "user"
  password: "user"
  dotnet-service: "dotnetapp"
  endpoints:
    updateStatus: UpdateNodesStatus
    updateTask: UpdateTaskCounter

# configuration of rabbitmq mqtt connection
mqtt:
  hostname: "rabbitmq-broker"
  username: "user"
  password: "user"
